.TH LINTHESIA "1" "January 2022" "linthesia" "User Commands"
.SH NAME
linthesia \- A game of playing music
.SH SYNOPSIS
.B linthesia
[\fI\,OPTION\/\fR]... [\fI\,REPOSITORY\/\fR]...
.SH DESCRIPTION
.B linthesia
Linthesia is a game of playing music. Select a midi file...
.SH OPTIONS
Help Options:
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\fR
Show help options
.PP
Application Options:
.TP
\fB\-v\fR, \fB\-\-version\fR
Show the application?s version
.RE
.SH AUTHORS
Oscar
.br
Alberto Fanjul  <albfan@gnome.org>
